const internalError = {
    message: "Houve um problema interno, tente novamente ou mais tarde."
}

module.exports = {
    internalError
}